trigger:
- master

pool: Default

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*csproj'

#PAT toke for aws server - woccgxudmuqdmsh4wdkuudnarw2jay4fosm2nvsm4qpn65e75czq

    
